# fly.toml app configuration file generated for gratify-me on 2023-06-06T18:33:47+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gratify-me"
primary_region = "hkg"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
